In [1]:
import numpy as np
import scipy

In [2]:
a = np.array([
    [1, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 1, 1, 1],
])

In [4]:
a_pinv = np.linalg.pinv(a)
print(a_pinv)

[[ 0.33333333 -0.16666667  0.16666667]
 [ 0.33333333 -0.16666667  0.16666667]
 [-0.16666667  0.33333333  0.16666667]
 [-0.16666667  0.33333333  0.16666667]]


In [6]:
a_pinv @ a

array([[ 5.00000000e-01,  5.00000000e-01, -2.77555756e-17,
        -2.77555756e-17],
       [ 5.00000000e-01,  5.00000000e-01, -5.55111512e-17,
        -5.55111512e-17],
       [ 1.38777878e-16,  1.38777878e-16,  5.00000000e-01,
         5.00000000e-01],
       [ 1.38777878e-16,  1.38777878e-16,  5.00000000e-01,
         5.00000000e-01]])