# Assignment 1 (Modified Exercise 6.8: The QR algorithm)

In [20]:
import numpy as np


np.set_printoptions(precision=4)

In this exercise you’ll write a program to calculate the eigenvalues and eigenvectors of a real symmetric matrix
using the QR algorithm. The first challenge is to write a program that find the QR decomposition of a matrix.
Then we’ll use that decomposition to find the eigenvalues.

As described above, the QR decomposition expresses a real square matrix $\mathbf A$ in the form $\mathbf A = \mathbf Q\mathbf R$,
where $\mathbf A$ is an orthogonal matrix and $\mathbf R$ is an upper-triangular matrix. Given an $N\times N$ matrix $\mathbf A$ we can
compute the QR decomposition as follows.

Let us think of the matrix as a set of $N$ column vectors $\mathbf a_0, ..., \mathbf a_{N-1}$ thus:

$$\mathbf A = \begin{pmatrix}
| & | & | & \cdots \\
\mathbf a_0 & \mathbf a_1 & \mathbf a_2 & \cdots \\
| & | & | & \cdots
\end{pmatrix}$$

where we have numbered the vectors in Python fashion, starting from zero, which will be convenient when writing
the program. We now define two new sets of vectors

$\mathbf u_0, ..., \mathbf u_{N-1}$ and $\mathbf q_0, ..., \mathbf q_{N-1}$  as follows:

\begin{align}
    &\mathbf u_0 = \mathbf a_0, &\mathbf q_0=\frac{\mathbf u_0}{\|\mathbf u_0\|} \\
    &\mathbf u_0 = \mathbf a_1 - (\mathbf q_0 \cdot \mathbf a_1)\mathbf q_0, &\mathbf q_1=\frac{\mathbf u_1}{\|\mathbf u_1\|} \\
    &\mathbf u_0 = \mathbf a_2 - (\mathbf q_0 \cdot \mathbf a_2)\mathbf q_0 - (\mathbf q_1 \cdot \mathbf a_2)\mathbf q_1, &\mathbf q_2=\frac{\mathbf u_2}{\|\mathbf u_2\|} \\
\end{align}

and so forth. The general formulas or calculating $\mathbf u_i$ and $\mathbf q_i$ are

$$
\mathbf u_i = \mathbf a_i - \sum_{j=0}^{i - 1} (\mathbf q_j\cdot\mathbf a_i)\mathbf q_j, \quad \mathbf q_i=\frac{\mathbf u_i}{\|\mathbf u_i\|}
$$

Here, the vectors $\mathbf q_i$ are orthonormal, i.e., that they satisfy
$$
\mathbf q_i\cdot\mathbf q_j = \begin{cases}1 & \text{if $i = j$} \\ 0 & \text{if $i\neq j$}\end{cases}
$$

Now, rearranging the definition of the vectors, we have

\begin{aligned}
\mathbf a_0 &= \| \mathbf u_0 \| \mathbf q_0,\\
\mathbf a_1 &= \| \mathbf u_1 \| \mathbf q_1 + (\mathbf q_0 \cdot \mathbf a_1) \, \mathbf q_0,\\
\mathbf a_2 &= \| \mathbf u_2 \| \mathbf q_2 + (\mathbf q_0 \cdot \mathbf a_2) \, \mathbf q_0 + (\mathbf q_1 \cdot \mathbf a_2) \, \mathbf q_1,
\end{aligned}

and so on. Or we can group the vectors $\mathbf q_i$ together as the columns of a matrix and write all of these equations as
a single matrix equation

$$\mathbf A = 
\begin{pmatrix}
| & | & | & \cdots \\
\mathbf a_0 & \mathbf a_1 & \mathbf a_2 & \cdots \\
| & | & | & \cdots
\end{pmatrix}
=
\begin{pmatrix}
| & | & | & \cdots \\
\mathbf q_0 & \mathbf q_1 & \mathbf q_2 & \cdots \\
| & | & | & \cdots
\end{pmatrix}
\begin{pmatrix}
\|\mathbf u_0\| & \mathbf q_0\cdot\mathbf a_1 & \mathbf q_0\cdot\mathbf a_2 & \cdots \\
0 & \|\mathbf u_1\| & \mathbf q_1\cdot\mathbf a_2 & \cdots \\
0 & 0 & \|\mathbf u_2\| & \cdots \\
\vdots & \vdots & \vdots & \ddots
\end{pmatrix}
$$
(If this looks complicated it's worth multiplying out the matrices on the right to verify for yourself that you get
the correct expressions for the $\mathbf a_i$.)

Notice now that the first matrix on the right-hand side of this equation, the matrix with columns $\mathbf q_i$, is
orthogonal, because the vectors $\mathbf q_i$ are orthonormal, and the second matrix is upper triangular. In other words,
we have found the QR decomposition $\mathbf A = \mathbf Q\mathbf R$. The matrices $\mathbf Q$ and $\mathbf R$ are

$$
\mathbf Q=\begin{pmatrix}
| & | & | & \cdots \\
\mathbf q_0 & \mathbf q_1 & \mathbf q_2 & \cdots \\
| & | & | & \cdots
\end{pmatrix}
\quad
\mathbf R=\begin{pmatrix}
\|\mathbf u_0\| & \mathbf q_0\cdot\mathbf a_1 & \mathbf q_0\cdot\mathbf a_2 & \cdots \\
0 & \|\mathbf u_1\| & \mathbf q_1\cdot\mathbf a_2 & \cdots \\
0 & 0 & \|\mathbf u_2\| & \cdots \\
\vdots & \vdots & \vdots & \ddots
\end{pmatrix}
$$


1-1) Write a Python function that takes as its argument a real square matrix $\mathbf A$ and returns the two matrices $\mathbf Q$ and $\mathbf R$ that forms its QR decomposition. As a test case, try out your function on the matrix

$$
A = \begin{pmatrix}
1 & 4 & 8 & 4 \\
4 & 2 & 3 & 7 \\
8 & 3 & 6 & 9 \\
4 & 7 & 9 & 2
\end{pmatrix}
$$

Check the results by multiplying $\mathbf Q$ and $\mathbf R$ together to recover the original matrix $\mathbf A$ again.

In [ ]:
def qr_decompose(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j].copy()
        for i in range(j):
            R[i, j] = np.sum(Q[:, i] * A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        if R[j, j] == 0:
            raise ValueError("columns of A are not linearly independent.")
        Q[:, j] = v / R[j, j]
    
    return Q, R

In [22]:
A = np.array(
    [[1, 4, 8, 4],
     [4, 2, 3, 7],
     [8, 3, 6, 9],
     [4, 7, 9, 2]]
)
Q, R = qr_decompose(A)

In [23]:
Q

array([[ 0.1015,  0.5585,  0.8098,  0.1484],
       [ 0.4061, -0.1069, -0.1415,  0.8964],
       [ 0.8123, -0.3809,  0.23  , -0.3771],
       [ 0.4061,  0.7291, -0.5209, -0.1793]])

In [24]:
R

array([[ 9.8489,  6.4982, 10.5596, 11.3719],
       [ 0.    ,  5.9811,  8.4235, -0.4843],
       [ 0.    ,  0.    ,  2.7459,  3.2767],
       [ 0.    ,  0.    ,  0.    ,  3.1159]])

Check $\mathbf Q^\top\mathbf Q = \mathbf I$

In [25]:
with np.printoptions(suppress=True):
    print(Q.T @ Q)

[[ 1. -0. -0. -0.]
 [-0.  1.  0. -0.]
 [-0.  0.  1.  0.]
 [-0. -0.  0.  1.]]


Check $\mathbf Q \mathbf R = \mathbf A$

In [26]:
print(Q @ R)

[[1. 4. 8. 4.]
 [4. 2. 3. 7.]
 [8. 3. 6. 9.]
 [4. 7. 9. 2.]]


1-2) Using your function, write a complete program to calculate the eigenvalues and eigenvectors of a real symmetric matrix using the QR algorithm. Continue the calculation until the magnitude of every off-diagonal element of the matrix is smaller than $10^{-6}$. Test your program on the example matrix above. You
should find that the eigenvalues are 1, 21, −3, and −8.

In [27]:
def eigh_by_qr(A, threshold = 1e-6, max_iterations = 80):
    Q, R = qr_decompose(A)
    U = Q.copy()
    for _ in range(max_iterations):
        B = R @ Q
        if np.allclose(B, np.diag(np.diag(B)), rtol=0., atol=threshold):
            return np.diag(B), U
        Q[:, :], R[:, :] = qr_decompose(B)
        U[:, :] = U @ Q
        
        
    print(f"maximum iteration(={max_iterations}) is reached.")
    return np.diag(R @ Q), U

In [32]:
eigenvalue, eigenvectors = eigh_by_qr(A)
eigenvalue_np, eigenvectors_np = np.linalg.eigh(A)

with np.printoptions(suppress=True):
    print(eigenvectors @ eigenvectors.T)
    print(eigenvectors @ np.diag(eigenvalue) @ eigenvectors.T)
    
np.sort(eigenvalue), np.sort(eigenvalue_np)

[[ 1. -0.  0. -0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1.  0.]
 [-0. -0.  0.  1.]]
[[1. 4. 8. 4.]
 [4. 2. 3. 7.]
 [8. 3. 6. 9.]
 [4. 7. 9. 2.]]


(array([-8., -3.,  1., 21.]), array([-8., -3.,  1., 21.]))